services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - REDIS_URL=redis://redis:6379/1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=fikrly_db
      - DB_USER=postgres
      - DB_PASSWORD=fikrly_uz
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - redis
      - db
    # Command to run when starting the container (ensures migrations are run)
    command: >
      sh -c "npm run build:css &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:7-alpine

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fikrly_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fikrly_uz

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --token eyJhIjoiMWU4NDJiMjZlODFhOTM0Njk5NTA0YWIyNTFlZWE3ZWIiLCJ0IjoiODVjOWYxZjQtMjJjMi00ZWQ2LTkwOGItMGUyMmUyYTIzYmEwIiwicyI6IlltVXpNbVk0T0RFdFlUZGhOQzAwTm1NeUxUbGpZV1V0T0RaaU9XWTVNek0wTTJZMSJ9
    depends_on:
      - nginx

volumes:
  postgres_data_dev:
